 spring.jpa.hibernate.ddl-auto=update
 #spring.datasource.url=jdbc:mysql://localhost:3306/basEze?useSSL=false&serverTimezone=UTC
 spring.datasource.url=jdbc:mysql://root:GySD9PYY1Rf7eHpGWZk6@containers-us-west-195.railway.app:7293/railway?useSSL=false&serverTimezone=UTC

 spring.datasource.username=root
 #spring.datasource.password=MlX80intro
 spring.datasource.password=GySD9PYY1Rf7eHpGWZk6
 spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


jwt.secret = secret
jwt.expiration = 36000000

