 spring.jpa.hibernate.ddl-auto=update
 #spring.datasource.url=jdbc:mysql://localhost:3306/basEze?useSSL=false&serverTimezone=UTC
 spring.datasource.url=jdbc:mysql://root:AHZMo4EF3jAdAPZai9Hd@containers-us-west-165.railway.app:6320/railway?useSSL=false&serverTimezone=UTC

 spring.datasource.username=root
 #spring.datasource.password=MlX80intro
 spring.datasource.password=AHZMo4EF3jAdAPZai9Hd
 spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


jwt.secret = secret
jwt.expiration = 36000

