 spring.jpa.hibernate.ddl-auto=update
 spring.datasource.url=jdbc:mysql://root:4DdrGbuAA1bag4cgKpKL@containers-us-west-20.railway.app:5456/railway?useSSL=false&serverTimezone=UTC
 spring.datasource.username=root
 spring.datasource.password=4DdrGbuAA1bag4cgKpKL
 spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret = secret
jwt.expiration = 3600 
