 spring.jpa.hibernate.ddl-auto=update
 #spring.datasource.url=jdbc:mysql://localhost:3306/basEze?useSSL=false&serverTimezone=UTC
 spring.datasource.url=jdbc:mysql://root:E28cX75OeqPKwgYG00Fw@containers-us-west-53.railway.app:6161/railway?useSSL=false&serverTimezone=UTC

 spring.datasource.username=root
 #spring.datasource.password=MlX80intro
 spring.datasource.password=E28cX75OeqPKwgYG00Fw
 spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


jwt.secret = secret
jwt.expiration = 3600
