 spring.jpa.hibernate.ddl-auto=update
 #spring.datasource.url=jdbc:mysql://localhost:3306/basEze?useSSL=false&serverTimezone=UTC
 spring.datasource.url=jdbc:mysql://root:5B0h9pAyg8S6tvGBLsYc@containers-us-west-197.railway.app:7163/railway?useSSL=false&serverTimezone=UTC

 spring.datasource.username=root
 #spring.datasource.password=MlX80intro
 spring.datasource.password=5B0h9pAyg8S6tvGBLsYc
 spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


jwt.secret = secret
jwt.expiration = 36000

