 spring.jpa.hibernate.ddl-auto=update
 #spring.datasource.url=jdbc:mysql://localhost:3306/basEze?useSSL=false&serverTimezone=UTC
 spring.datasource.url=jdbc:mysql://root:GYeM6gArE3S9s7V13vBO@containers-us-west-137.railway.app:7844/railway?useSSL=false&serverTimezone=UTC

 spring.datasource.username=root
 #spring.datasource.password=MlX80intro
 spring.datasource.password=GYeM6gArE3S9s7V13vBO
 spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


jwt.secret = secret
jwt.expiration = 36000

